import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, X, Maximize2 } from 'lucide-react';
import type { Language } from '../types';
import { parseMarkdownContent, renderContentBlocks } from '../utils/markdownParser';

interface ChatAnalysisPanelProps {
  content: string;
  language: Language;
  onClose: () => void;
}

export const ChatAnalysisPanel: React.FC<ChatAnalysisPanelProps> = ({ content, language, onClose }) => {
  const blocks = parseMarkdownContent(content);

  return (
    <motion.div
      initial={{ opacity: 0, y: 20, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -10, scale: 0.98 }}
      transition={{ type: 'spring', stiffness: 300, damping: 30 }}
      className="card relative overflow-hidden group"
    >
      {/* Background decoration */}
      <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
        <Maximize2 size={80} className="text-primary" />
      </div>

      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-primary/10 border border-primary/20 flex items-center justify-center shadow-[inset_0_0_10px_rgba(29,212,180,0.1)]">
            <Sparkles size={16} className="text-primary" />
          </div>
          <div>
            <h3 className="text-[10px] font-black text-text-primary uppercase tracking-[0.2em]">
              {language === 'en' ? 'AI Chat Analysis' : 'Análisis del Chat IA'}
            </h3>
            <p className="text-[9px] font-bold text-text-muted uppercase tracking-wider mt-0.5">
              {language === 'en' ? 'Expanded view from assistant' : 'Vista expandida del asistente'}
            </p>
          </div>
        </div>

        <button
          onClick={onClose}
          className="w-8 h-8 rounded-lg bg-[#131b2f] border border-border flex items-center justify-center text-text-muted hover:text-error hover:border-error/30 hover:bg-error/10 transition-all active:scale-90"
          aria-label={language === 'en' ? 'Close panel' : 'Cerrar panel'}
        >
          <X size={14} />
        </button>
      </div>

      {/* Content */}
      <div className="bg-[#131b2f] border border-border rounded-[24px] p-6 md:p-8 relative">
        <div className="prose prose-invert prose-sm max-w-none text-text-secondary leading-relaxed font-medium">
          {renderContentBlocks(blocks, 'cap')}
        </div>
      </div>

      {/* Footer */}
      <div className="mt-6 flex items-center justify-between">
        <p className="text-[9px] text-text-muted font-bold uppercase tracking-wider italic">
          {language === 'en'
            ? '* Response generated by AI based on your question.'
            : '* Respuesta generada por IA basada en tu pregunta.'}
        </p>
        <button
          onClick={onClose}
          className="text-[10px] font-black text-text-muted hover:text-error flex items-center gap-2 transition-colors uppercase tracking-widest"
        >
          <X size={12} />
          {language === 'en' ? 'Close' : 'Cerrar'}
        </button>
      </div>
    </motion.div>
  );
};
